### ISSUE TITLE
[已解决]部署过程中提示这个错误，请问如何解决。

### ISSUE THREAD

**Issue by shmilyabyy** [theme-keep/hexo-deploy-github-pages-action#12]
![image](https://user-images.githubusercontent.com/77541484/208293477-84f456e7-5c39-483e-b5a2-43602955667f.png)
已经解决了，是我的问题。非常抱歉

**Comment by Hakuin123** [comment]
@shmilyabyy 请问如何解决？我也遇到了此问题
