### ISSUE TITLE
关于CNAME的问题

### ISSUE THREAD

**Issue by Extious** [theme-keep/hexo-deploy-github-pages-action#16]
使用这个action的话，每次push自动化部署之后，都要重新create CNAME一下吗，force push之后public下的CNAME文件刷掉了好像

**Comment by Extious** [comment]
而且，这样提交一次好像每一篇文章的更新时间都改变了

**Comment by XPoet** [comment]
如果填写了 CNAME，这个 action 会帮你自动创建 CNAME

**Comment by XPoet** [comment]
文章更新时间全部变成一样这个问题，参与 [此文](https://keep.xpoet.cn/2023/11/%E5%A6%82%E4%BD%95%E8%A7%A3%E5%86%B3-GitHub-Actions-%E8%87%AA%E5%8A%A8%E9%83%A8%E7%BD%B2%E5%90%8E%E6%96%87%E7%AB%A0%E6%9B%B4%E6%96%B0%E6%97%B6%E9%97%B4%E5%BC%82%E5%B8%B8%E7%9A%84%E9%97%AE%E9%A2%98/) 解决。

**Comment by Extious** [comment]
了解了，感谢解答！！！
