### ISSUE TITLE
每次action运行完后到了页面上我的更新时间和发布时间都会被刷新一次

### ISSUE THREAD

**Issue by FreeDivers** [theme-keep/hexo-deploy-github-pages-action#7]

**Comment by jackeyzzz12138** [comment]
你好，我也遇到了同样的问题，请问有解决方法吗？

**Comment by FreeDivers** [comment]
> 你好，我也遇到了同样的问题，请问有解决方法吗？

因为博文的更新时间看的是 Front-matter 中的 updated 给定的时间。所以只要博客在写之前就定义好了 updated，文章更新时间就不会随着自动部署变化。

所提前在文章的 front matter 中设定好 updated 就可以了。

在`博客文件目录\scaffolds\post.md`里加上以下内容
```
date: {{ date }}
updated: {{ date }}
```
以后你创建的`.md`就在命令行输入
`hexo new post "标题名称"`就好了

**Comment by jackeyzzz12138** [comment]
> > 你好，我也遇到了同样的问题，请问有解决方法吗？
> 
> 因为博文的更新时间看的是 Front-matter 中的 updated 给定的时间。所以只要博客在写之前就定义好了 updated，文章更新时间就不会随着自动部署变化。
> 
> 所提前在文章的 front matter 中设定好 updated 就可以了。
> 
> 在`博客文件目录\scaffolds\post.md`里加上以下内容
> 
> ```
> date: {{ date }}
> updated: {{ date }}
> ```
> 
> 以后你创建的`.md`就在命令行输入 `hexo new post "标题名称"`就好了

感谢您的解答：）
